return ({
"1943" : ["Fire","Special","Loop","Start"]
"1943j" : ["Fire","Special","Loop","Start"]
"1943ja" : ["Fire","Special","Loop","Start"]
"1943u" : ["Fire","Special","Loop","Start"]
"1943ua" : ["Fire","Special","Loop","Start"]
"19xx" : ["Fire","Bomb","Start"]
"19xxa" : ["Fire","Bomb","Start"]
"19xxar1" : ["Fire","Bomb","Start"]
"19xxb" : ["Fire","Bomb","Start"]
"19xxh" : ["Fire","Bomb","Start"]
"19xxj" : ["Fire","Bomb","Start"]
"19xxjr1" : ["Fire","Bomb","Start"]
"19xxjr2" : ["Fire","Bomb","Start"]
"19xxu" : ["Fire","Bomb","Start"]
"3countb" : ["Punch","Kick","Jump","Taunt","Start","Select"]
"aerofgts" : ["Fire","Bomb","Start"]
"aodk" : ["Punch","Kick","Jump","No Use","Start","Select"]
"aof" : ["Punch","Kick","Strong Attack / Throw","Taunt","Start","Select"]
"aof2" : ["Punch","Kick","Weak Punch / Kick","Taunt","Start","Select"]
"aof2a" : ["Punch","Kick","Weak Punch / Kick","Taunt","Start","Select"]
"aof3" : ["Punch","Kick","Blow Away Attack","Taunt","Start","Select"]
"aof3k" : ["Punch","Kick","Blow Away Attack","Taunt","Start","Select"]
"armwar" : ["Attack","Jump","Weapon","Start"]
"armwara" : ["Attack","Jump","Weapon","Start"]
"armwarar1" : ["Attack","Jump","Weapon","Start"]
"armwarr1" : ["Attack","Jump","Weapon","Start"]
"armwaru" : ["Attack","Jump","Weapon","Start"]
"armwaru1" : ["Attack","Jump","Weapon","Start"]
"asurabld" : ["Light Attack","Hard Attack","Powerful Attack","Start"]
"asurabus" : ["Light Attack","Hard Attack","Powerful Attack","Start"]
"asurabusa" : ["Light Attack","Hard Attack","Powerful Attack","Start"]
"avengrgs" : ["Light Punch","Strong Punch","Light Kick","Strong Kick","Start"]
"avengrgsj" : ["Light Punch","Strong Punch","Light Kick","Strong Kick","Start"]
"beastrzr" : ["Punch","Kick","Beast","Start"]
"beastrzra" : ["Punch","Kick","Beast","Start"]
"beastrzrb" : ["Punch","Kick","Beast","Start"]
"blazstar" : ["Fire","Alternative Fire","No Use","No Use","Start","Select"]
"bldyroar" : ["Punch","Kick","Beast","Start"]
"bldyror2" : ["Punch","Kick","Beast","Guard","Start"]
"bldyror2a" : ["Punch","Kick","Beast","Guard","Start"]
"bldyror2j" : ["Punch","Kick","Beast","Guard","Start"]
"bldyror2u" : ["Punch","Kick","Beast","Guard","Start"]
"bloodstm" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm10" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm11" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm21" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm22" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"breakers" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"breakrev" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"brival" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"brivalj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"crusnusa" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa21" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa40" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa41" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa44" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld13" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld17" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld19" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld20" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld23" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld24" : ["Accelerator Pedal","Brake Pedal"]
"ct2k3sa" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"ct2k3sp" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"cthd2003" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"cybots" : ["Attack 1","Attack 2","Boost","Weapon","Start"]
"cybotsj" : ["Attack 1","Attack 2","Boost","Weapon","Start"]
"cybotsjd" : ["Attack 1","Attack 2","Weapon","Boost"]
"cybotsu" : ["Attack 1","Attack 2","Boost","Weapon","Start"]
"cybotsud" : ["Attack 1","Attack 2","Weapon","Boost"]
"dankuga" : ["Weak Punch","Medium Punch","Strong Punch","Level 4 Punch","Level 5 Punch","Weak Kick","Medium Kick","Strong Kick","Level 4 Kick","Level 5 Kick","Start"]
"daraku" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"dbz" : ["Punch","Kick","Hard Attack","Start"]
"dbz2" : ["Weak Punch","Strong Punch","Powerful Punch","Weak Kick","Strong Kick","Powerful Kick","Start"]
"dbza" : ["Punch","Kick","Hard Attack","Start"]
"doapp" : ["Punch","Kick","Hold","Start"]
"doappk" : ["Punch","Kick","Hold","Start"]
"doubledr" : ["Weak Attack","Medium Attack","Strong Attack","Super Attack","Start","Select"]
"dstlk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlka" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlkh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlku" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlku1d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"dstlkur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ehrgeiz" : ["Weak Low Attack","Strong Low Attack","Weak High Attack","Strong High Attack","Mid Attack","Special Attack","Guard","Start"]
"ehrgeizja" : ["Weak Low Attack","Strong Low Attack","Weak High Attack","Strong High Attack","Mid Attack","Special Attack","Guard","Start"]
"ehrgeizua" : ["Weak Low Attack","Strong Low Attack","Weak High Attack","Strong High Attack","Mid Attack","Special Attack","Guard","Start"]
"fatfursp" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfurspa" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfurwa" : ["Punch","Kick","Powerful Attack","3D Movement","Start"]
"fatfury1" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"fatfury2" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfury3" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"ffreveng" : ["Weak Punch","Strong Punch","Special","Weak Kick","Strong Kick","Taunt"]
"ffrevng10" : ["Weak Punch","Strong Punch","Special","Weak Kick","Strong Kick","Taunt"]
"fghthist" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthista" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistjb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistub" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistuc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fgtlayer" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fightfev" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"fightfeva" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"fitfight" : ["Punch","Kick","Strong Attack","Taunt"]
"fswords" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"galaxyfg" : ["Weak Attack","Medium Attack","Strong Attack","Taunt","Start","Select"]
"garou" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"garoubl" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"garouh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"garouha" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"garoup" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"gaxeduel" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"gblchmp" : ["Weak Punch","Medium Punch","Strong Punch","Level 4 Punch","Level 5 Punch","Weak Kick","Medium Kick","Strong Kick","Level 4 Kick","Level 5 Kick","Start"]
"gowcaizr" : ["Quick Punch","Quick Kick","Strong Punch","Strong Kick","Start","Select"]
"groovef" : ["Weak Punch","Strong Punch","Overhead Attack","Weak Kick","Strong Kick","Dash Attack","Taunt"]
"histryma" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"holo" : ["Weak Attack","Strong Attack","Start"]
"hsf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hsf2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hsf2d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"hsf2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hsf2j1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hvnsgate" : ["Guard","Punch","Kick","Start"]
"jgakuen" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"jgakuen1" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"jojo" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoba" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojobaj" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojobajr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojoban" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojobane" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojobaner1" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojobanr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojobar1" : ["Light Attack","Medium Attack","Heavy Attack","Stand Button","Taunt"]
"jojoj" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojojr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojojr2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojon" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojonr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojonr2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojor1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojor2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojou" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojour1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojour2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"kabukikl" : ["Weak Slash","Medium Slash","Strong Slash","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"kaiserkn" : ["Weak Punch","Medium Punch","Strong Punch","Level 4 Punch","Level 5 Punch","Weak Kick","Medium Kick","Strong Kick","Level 4 Kick","Level 5 Kick","Start"]
"kaiserknj" : ["Weak Punch","Medium Punch","Strong Punch","Level 4 Punch","Level 5 Punch","Weak Kick","Medium Kick","Strong Kick","Level 4 Kick","Level 5 Kick","Start"]
"karatedo" : ["Move Back / Block","Duck","Move forward","Jump"]
"karatevs" : ["Move Back / Block","Duck","Move forward","Jump"]
"karatour" : ["Attack","Jump","Start"]
"karatourj" : ["Attack","Jump","Start"]
"karnovr" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start","Select"]
"kchamp" : ["Move Back / Block","Duck","Move forward","Jump"]
"kchampvs" : ["Move Back / Block","Duck","Move forward","Jump"]
"kchampvs2" : ["Move Back / Block","Duck","Move forward","Jump"]
"kchampvs3" : ["Move Back / Block","Duck","Move forward","Jump"]
"kchampvs4" : ["Move Back / Block","Duck","Move forward","Jump"]
"kf10thep" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k2mp" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k2mp2" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k2pla" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k2pls" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k3bl" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k3bla" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k3pcb" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kf2k3pl" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k3upl" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kf2k5uni" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"killbld" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"killbld104" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"killbld106" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"kinst" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"kinst13" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst14" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"kinst210" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst211" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst213" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst2k3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst2k4" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinst2uk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"kinstb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kinstp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"kizuna" : ["Punch","Kick","Weapon Strike","Tag","Start","Select"]
"kizuna4p" : ["Punch","Kick","Weapon Strike","Tag","Start","Select"]
"kof10th" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof2000" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2000n" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2001" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2001h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2002" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2002b" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof2003" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2003h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2k4se" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof94" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof95" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof95a" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof95h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof96" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof96h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof97" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof97h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof97k" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof97oro" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof97pls" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof98" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98a" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98k" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98ka" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98umh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof99" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99e" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99k" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99ka" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99p" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kog" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"lastblad" : ["Weak Slash","Strong Slash","Weak Kick","Repel","Taunt","Select"]
"lastbladh" : ["Weak Slash","Strong Slash","Weak Kick","Repel","Taunt","Select"]
"lastbld2" : ["Weak Slash","Medium Slash","Weak Kick","Repel","Taunt","Select"]
"lastsold" : ["Weak Slash","Strong Slash","Weak Kick","Repel","Taunt","Select"]
"mace" : ["Quick Attack","Strong Attack","Kick","Evade","Start"]
"macea" : ["Quick Attack","Strong Attack","Kick","Evade","Start"]
"martmast" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmast102c" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmast103c" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmast104c" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmastc" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmastc102" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmastc103" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmasttw" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"matrim" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"matrimbl" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"mbomberj" : ["Attack","Jump","Start"]
"mbombrd" : ["Grab","Attack","Jump","Start"]
"mbombrdj" : ["Grab","Attack","Jump","Start"]
"mk" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r31e" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r32e" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2chal" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r11" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r14" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r20" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r21" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r30" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r42" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk2r91" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mk3" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk3mdb" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mk3p40" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mk3r10" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mk3r20" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mk3snes" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mk4" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk4a" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mk4b" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"mkla1" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkla2" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkla3" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkla4" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mknifty" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mknifty666" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkprot4" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkprot8" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkprot9" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkr4" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mktturbo" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkyawdim" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkyawdim2" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkyawdim3" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkyawdim4" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkyturbo" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"mkyturboe" : ["High Punch","Low Punch","Block","High Kick","Low Kick"]
"msh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"msha" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshbr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshvsf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfa1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfb1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfj2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfu1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfu1d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mtlchamp" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchamp1" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampa" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampj" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampu" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampu1" : ["High Attack","Mid Attack","Low Attack","Start"]
"mvsc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvsca" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvsch" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscjsing" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"ninjamas" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start","Select"]
"nwarr" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarra" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarrb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarrh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarru" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarrud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"pfghtj" : ["Punch","Kick","Special","Taunt"]
"pgear" : ["Attack","Jump","Weapon","Start"]
"pgearr1" : ["Attack","Jump","Weapon","Start"]
"plegends" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"plegendsj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"plsmaswd" : ["Horizontal Attack","Vertical Attack","Kick","Movement","Taunt"]
"plsmaswda" : ["Horizontal Attack","Vertical Attack","Kick","Movement","Taunt"]
"powerins" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"powerinsa" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick"]
"powerinsb" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick"]
"powerinsj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"primrag2" : ["High Quick","High Fierce","High Power","Low Quick","Low Fierce","Low Power","Taunt"]
"primrage" : ["High Quick / Start","High Fierce","Low Quick","Low Fierce"]
"primrage20" : ["High Quick / Start","High Fierce","Low Quick","Low Fierce"]
"psoldier" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"pwrinst2" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"pwrinst2j" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"ragnagrd" : ["Light Punch","Light Kick","Heavy Punch","Heavy Kick","Start","Select"]
"ragnagrd" : ["Light Punch","Light Kick","Heavy Punch","Heavy Kick","Start","Select"]
"rbff1" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff1a" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff1k" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff1ka" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff2" : ["Punch","Kick","Powerful Attack","Move to Other Fighting Plane","Start","Select"]
"rbff2h" : ["Punch","Kick","Powerful Attack","Move to Other Fighting Plane","Start","Select"]
"rbff2k" : ["Punch","Kick","Powerful Attack","Move to Other Fighting Plane","Start","Select"]
"rbffspec" : ["Punch","Kick","Powerful Attack","Move to Other Fighting Plane","Start","Select"]
"rbffspeck" : ["Punch","Kick","Powerful Attack","Move to Other Fighting Plane","Start","Select"]
"rdft2" : ["Fire","Bomb","Start"]
"rdft2a" : ["Fire","Bomb","Start"]
"rdft2aa" : ["Fire","Bomb","Start"]
"rdft2it" : ["Fire","Bomb","Start"]
"rdft2j" : ["Fire","Bomb","Start"]
"rdft2ja" : ["Fire","Bomb","Start"]
"rdft2jb" : ["Fire","Bomb","Start"]
"rdft2jc" : ["Fire","Bomb","Start"]
"rdft2s" : ["Fire","Bomb","Start"]
"rdft2t" : ["Fire","Bomb","Start"]
"rdft2u" : ["Fire","Bomb","Start"]
"rdft2us" : ["Fire","Bomb","Start"]
"redearth" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"redearthr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"rfjet" : ["Fire","Bomb","Start"]
"rfjeta" : ["Fire","Bomb","Start"]
"rfjetj" : ["Fire","Bomb","Start"]
"rfjets" : ["Fire","Bomb","Start"]
"rfjetsa" : ["Fire","Bomb","Start"]
"rfjett" : ["Fire","Bomb","Start"]
"rfjetu" : ["Fire","Bomb","Start"]
"ringdest" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdesta" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdestb" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdesth" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdstd" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick"]
"rotd" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"rotd" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"rotdh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"rotdh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"rvschool" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"rvschoola" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"rvschoolu" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"s1945iii" : ["Fire","Bomb","Start"]
"s1945p" : ["Fire","Bomb","No Use","No Use","Start"]
"sams64_2" : ["Weak Attack","Medium Attack","Strong Attack","3D Movement","Start"]
"sams64" : ["Weak Attack","Strong Attack","Throw","3D Movement","Start"]
"samsh5sp" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Meditation","Start","Select"]
"samsh5sph" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Meditation","Start","Select"]
"samsh5spho" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Meditation","Start","Select"]
"samsho" : ["Weak Slash","Medium Slash","Strong Slash","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"samsho2" : ["Weak Slash","Medium Slash","Strong Slash","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"samsho2k" : ["Weak Slash","Medium Slash","Strong Slash","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"samsho2ka" : ["Weak Slash","Medium Slash","Strong Slash","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"samsho3" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho3h" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho4" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho4k" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho5" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Meditation","Start","Select"]
"samsho5a" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Meditation","Start","Select"]
"samsho5b" : ["Weak Slash","Medium Slash","Kick","Meditation"]
"samsho5h" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Meditation","Start","Select"]
"samshoh" : ["Weak Slash","Medium Slash","Strong Slash","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"savagere" : ["Punch","Kick","Weapon Strike","Dimensional Attack","Start","Select"]
"schamp" : ["Barrier","Punch","Kick","Start"]
"sdodgeb" : ["Throw Ball","Pass","Jump","Fake","Start"]
"sf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2acc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2acca" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2accp2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2amf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2amf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2b" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2bhh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2ce" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceblp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2cebltw" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2ceea" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2cejb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2cejc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2cet" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceub" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceuc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ea" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2dkot2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2dongb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2eb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ebbl" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2ebbl2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2ebbl3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2ed" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ee" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ef" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2em" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2en" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2hf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2hfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2hfu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2j17" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jl" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2koryu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m10" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m4" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m5" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m6" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m7" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m8" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2m9" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2mdt" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2mdta" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2mdtb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2qp1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2rb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2rb2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2rb3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2red" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2rk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2stt" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2thndr" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2ua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ub" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ue" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ug" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ui" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2um" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2v004" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sf2yyc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sfa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa2u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa2ur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3b" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3hr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3ud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3ur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3us" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfach" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfad" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfan" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfar2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfar3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfau" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfex" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2p" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2pa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2ph" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2pj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2pu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2u1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sfex2u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2u1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexpj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexpj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexpu1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfight" : ["Barrier","Punch","Kick","Start"]
"sfiii" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2n" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3n" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3nr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3r1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3ur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiia" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiih" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiij" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiin" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiina" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiiu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfjan" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sftm" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftm110" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftm111" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftmj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"sftmj112" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftmj114" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfw" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfz2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2ad" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2al" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2ald" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2b" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2br1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2jd" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2n" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3ar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3jr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3jr2d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfza" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzbch" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzbr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzch" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzhr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzjr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sgemf" : ["Punch","Kick","Special","Taunt"]
"sgemfa" : ["Punch","Kick","Special","Taunt"]
"sgemfd" : ["Punch","Kick","Special","Taunt"]
"sgemfh" : ["Punch","Kick","Special","Taunt"]
"slammast" : ["Attack","Jump","Start"]
"slammastu" : ["Attack","Jump","Start"]
"slampic" : ["Attack","Jump"]
"smbomb" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"smbombr1" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"sncwgltd" : ["Fire","Bomb","Start"]
"soulclbr" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrja" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrjb" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrjc" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrub" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbruc" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrwb" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledge" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgea" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgeja" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgeua" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgeuc" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"ssf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2ar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2jr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2mdb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"ssf2r1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2t" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2ta" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tad" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"ssf2tb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tba" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbd" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"ssf2tbh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2th" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2ud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"ssf2xj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2xjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2xjr1d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick"]
"ssf2xjr1r" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssoldier" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"starglad" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"stargladj" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"stargld2" : ["Horizontal Attack","Vertical Attack","Kick","Movement","Taunt"]
"suikoenb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"survarts" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"survartsj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"survartsu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"svc" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"svcboot" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"svcpcb" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"svcpcba" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"svcplus" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"svcplusa" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"svcsplus" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"tattass" : ["High Punch","Low Punch","Special / Tattoo / Fatality","Block","High Kick","Low Kick","Start"]
"tattassa" : ["High Punch","Low Punch","Special / Tattoo / Fatality","Block","High Kick","Low Kick","Start"]
"tekken" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2a" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2b" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2aa" : ["Left Punch","Right Punch","Left Kick","Right Kick"]
"tekken2ab" : ["Left Punch","Right Punch","Left Kick","Right Kick"]
"tekken2jb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2jc" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2ub" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3a" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3b" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3aa" : ["Left Punch","Right Punch","Left Kick","Right Kick"]
"tekken3ab" : ["Left Punch","Right Punch","Left Kick","Right Kick"]
"tekken3ae" : ["Left Punch","Right Punch","Left Kick","Right Kick"]
"tekken3ja" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3je1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3ua" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3ud" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekkenac" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekkenb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekkenab" : ["Left Punch","Right Punch","Left Kick","Right Kick"]
"tekkenjb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tektagt" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtac" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag"]
"tektagtac1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag"]
"tektagtc1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtja" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtjb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtjc1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtub" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtuc1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"timekill" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill100" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill121" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill121a" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill131" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill132i" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"tkdensho" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"tkdenshoa" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"tophuntr" : ["Punch / Arm Stretch","Jump","Change Planes","Not Used","Start","Select"]
"tophuntrh" : ["Punch / Arm Stretch","Jump","Change Planes","Not Used","Start","Select"]
"ts2" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"ts2a" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"ts2j" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"umk3" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"umk3r10" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"umk3r11" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run"]
"vampj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vampja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vampjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vf" : ["Guard","Punch","Kick","Start"]
"vf2" : ["Guard","Punch","Kick","Start"]
"vf2a" : ["Guard","Punch","Kick","Start"]
"vf2b" : ["Guard","Punch","Kick","Start"]
"vf2o" : ["Guard","Punch","Kick","Start"]
"vhunt2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vhunt2d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vhunt2r1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vhuntj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntjr1s" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntjr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vsav" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsav2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsav2d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsava" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavd" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"wakuwak7" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start","Select"]
"wargods" : ["High Punch","Low Punch","Guard","High Kick","Low Kick","3-D Button","Start"]
"wargodsa" : ["High Punch","Low Punch","Guard","High Kick","Low Kick","3-D Button","Start"]
"wargodsb" : ["High Punch","Low Punch","Guard","High Kick","Low Kick","3-D Button","Start"]
"warzard" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"warzardr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"wh1" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh1h" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh1ha" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh2" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh2h" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh2j" : ["Punch","Kick","Taunt","Not Used","Start","Select"]
"whp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start","Select"]
"xmcota" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaar2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotab" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotah" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotahr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotajr" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotau" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmvsf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfar2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfar3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfjr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfjr3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfu1d" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfur2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
})