return ({
"1943" : ["Fire","Special","Start"]
"1943j" : ["Fire","Special","Start"]
"1943ja" : ["Fire","Special","Start"]
"1943u" : ["Fire","Special","Start"]
"1943ua" : ["Fire","Special","Start"]
"1943kai" : ["Fire","Special","Start"]
"1943mii" : ["Fire","Special","Start"]
"19xx" : ["Fire","Bomb","Start"]
"19xxa" : ["Fire","Bomb","Start"]
"19xxar1" : ["Fire","Bomb","Start"]
"19xxb" : ["Fire","Bomb","Start"]
"19xxh" : ["Fire","Bomb","Start"]
"19xxj" : ["Fire","Bomb","Start"]
"19xxjr1" : ["Fire","Bomb","Start"]
"19xxjr2" : ["Fire","Bomb","Start"]
"19xxu" : ["Fire","Bomb","Start"]
"3countb" : ["Punch","Kick","Jump","Taunt","Start","Select"]
"64street" : ["Attack","Jump","Start"]
"64streetj" : ["Attack","Jump","Start"]
"64streetja" : ["Attack","Jump","Start"]
"sonicwi3" : ["Fire","Bomb","Not Used","Not Used","Start","Select"]
"aerofgts" : ["Fire","Bomb","Start"]
"aerofgtst" : ["Fire","Bomb","Start"]
"sncwgltd" : ["Fire","Bomb","Start"]
"aodk" : ["Punch","Kick","Jump","No Use","Start","Select"]
"aliencha" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"alienchac" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"avsp" : ["Gun","Attack","Jump","Start"]
"avspa" : ["Gun","Attack","Jump","Start"]
"avsph" : ["Gun","Attack","Jump","Start"]
"avspj" : ["Gun","Attack","Jump","Start"]
"avspu" : ["Gun","Attack","Jump","Start"]
"arabianm" : ["Attack","Jump","Magic","Start"]
"arabianmu" : ["Attack","Jump","Magic","Start"]
"arabianmj" : ["Attack","Jump","Magic","Start"]
"armwar" : ["Attack","Jump","Weapon","Start"]
"armwara" : ["Attack","Jump","Weapon","Start"]
"armwarar1" : ["Attack","Jump","Weapon","Start"]
"armwarb" : ["Attack","Jump","Weapon","Start"]
"armwarr1" : ["Attack","Jump","Weapon","Start"]
"armwaru" : ["Attack","Jump","Weapon","Start"]
"armwaru1" : ["Attack","Jump","Weapon","Start"]
"pgear" : ["Attack","Jump","Weapon","Start"]
"pgearr1" : ["Attack","Jump","Weapon","Start"]
"aof" : ["Punch","Kick","Throw","Taunt","Start","Select"]
"aof2" : ["Punch","Kick","Throw","Taunt","Start","Select"]
"aof2a" : ["Punch","Kick","Throw","Taunt","Start","Select"]
"aof3" : ["Punch","Kick","Blow Away Attack","Taunt","Start","Select"]
"aof3k" : ["Punch","Kick","Blow Away Attack","Taunt","Start","Select"]
"asterix" : ["Attack","Jump","Start"]
"asterixaad" : ["Attack","Jump","Start"]
"asterixeaa" : ["Attack","Jump","Start"]
"asterixeac" : ["Attack","Jump","Start"]
"asterixj" : ["Attack","Jump","Start"]
"astrass" : ["Attack 1","Attack 2","Attack 3","Attack 4","Attack 5","Attack 6","Start"]
"asurabld" : ["Light Attack","Hard Attack","Powerful Attack","Start"]
"asurabus" : ["Light Attack","Hard Attack","Powerful Attack","Pause","Start"]
"asurabusj" : ["Light Attack","Hard Attack","Powerful Attack","Pause","Start"]
"asurabusja" : ["Light Attack","Hard Attack","Powerful Attack","Pause","Start"]
"asurabusjr" : ["Light Attack","Hard Attack","Powerful Attack","Pause","Start"]
"avengrgs" : ["Light Punch","Strong Punch","Light Kick","Strong Kick","Start"]
"avengrgsj" : ["Light Punch","Strong Punch","Light Kick","Strong Kick","Start"]
"ts2" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"ts2j" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"ts2ja" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"ts2u" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"ts2ua" : ["Roll Aways","Weak Slash","Hard Slash","Roll Towards","Weak Kick","Hard Kick","Taunt"]
"batcir" : ["Attack","Jump","Start"]
"batcira" : ["Attack","Jump","Start"]
"batcirj" : ["Attack","Jump","Start"]
"btlkroad" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"btlkroadk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"bigfight" : ["Attack","Jump","Start"]
"bigfightj" : ["Attack","Jump","Start"]
"blandia" : ["High Attack","Mid Attack","Low Attack","Start"]
"blazstar" : ["Fire","Break Attack","No Use","No Use","Start","Select"]
"bloodstm" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm104" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm110" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm210" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm220" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodstm221" : ["Back Arm","Front Arm","Block","Back Leg","Front Leg","Start"]
"bloodwar" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"oedfight" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"oedfighta" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"beastrzr" : ["Punch","Kick","Beast","Start"]
"beastrzra" : ["Punch","Kick","Beast","Start"]
"bldyroar" : ["Punch","Kick","Beast","Start"]
"bldyror2" : ["Punch","Kick","Beast","Guard","Start"]
"bldyror2a" : ["Punch","Kick","Beast","Guard","Start"]
"bldyror2j" : ["Punch","Kick","Beast","Guard","Start"]
"bldyror2u" : ["Punch","Kick","Beast","Guard","Start"]
"breakers" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"breakrev" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"brival" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"brivalj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dino" : ["Attack","Jump","Start"]
"dinoa" : ["Attack","Jump","Start"]
"dinoj" : ["Attack","Jump","Start"]
"dinou" : ["Attack","Jump","Start"]
"capsnk" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"capsnka" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"capsnkb" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"cvsgd" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"cvs2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"cvs2mf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"captcomm" : ["Attack","Jump","Start"]
"captcommj" : ["Attack","Jump","Start"]
"captcommjr1" : ["Attack","Jump","Start"]
"captcommr1" : ["Attack","Jump","Start"]
"captcommu" : ["Attack","Jump","Start"]
"crusnusa" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa11" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa20" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa21" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa40" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa41" : ["Accelerator Pedal","Brake Pedal"]
"crusnusa44" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld13" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld17" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld19" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld20" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld23" : ["Accelerator Pedal","Brake Pedal"]
"crusnwld24" : ["Accelerator Pedal","Brake Pedal"]
"cybots" : ["Attack 1","Attack 2","Boost","Weapon","Start"]
"cybotsj" : ["Attack 1","Attack 2","Boost","Weapon","Start"]
"cybotsu" : ["Attack 1","Attack 2","Boost","Weapon","Start"]
"dstlk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlka" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlkh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlku" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dstlkur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vampj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vampja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vampjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"doa" : ["Hold","Punch","Kick","Start"]
"doaa" : ["Hold","Punch","Kick","Start"]
"doaae" : ["Hold","Punch","Kick","Start"]
"doaab" : ["Hold","Punch","Kick","Start"]
"doab" : ["Hold","Punch","Kick","Start"]
"doapp" : ["Hold","Punch","Kick","Start"]
"doappk" : ["Hold","Punch","Kick","Start"]
"doa2m" : ["Hold","Punch","Kick","Start"]
"doa2" : ["Hold","Punch","Kick","Start"]
"doa2a" : ["Hold","Punch","Kick","Start"]
"denjinmk" : ["Attack","Jump","Start"]
"denjinmka" : ["Attack","Jump","Start"]
"grdians" : ["Attack","Jump","Projectile","Start"]
"grdiansa" : ["Attack","Jump","Projectile","Start"]
"doubledr" : ["Weak Attack","Medium Attack","Strong Attack","Super Attack","Start","Select"]
"dbz" : ["Punch","Kick","Hard Attack","Start"]
"dbza" : ["Punch","Kick","Hard Attack","Start"]
"dbz2" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"drgnmst" : ["Weak Punch","Medium Punch","Weak Kick","Medium Kick","Start"]
"drgnmst2" : ["Weak Punch","Medium Punch","Weak Kick","Medium Kick","Start"]
"dragoona" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"dragoonj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"ddtod" : ["Attack","Jump","Item","Select","Start"]
"ddtoda" : ["Attack","Jump","Item","Select","Start"]
"ddtodar1" : ["Attack","Jump","Item","Select","Start"]
"ddtodh" : ["Attack","Jump","Item","Select","Start"]
"ddtodhr1" : ["Attack","Jump","Item","Select","Start"]
"ddtodhr2" : ["Attack","Jump","Item","Select","Start"]
"ddtodj" : ["Attack","Jump","Item","Select","Start"]
"ddtodjr1" : ["Attack","Jump","Item","Select","Start"]
"ddtodjr2" : ["Attack","Jump","Item","Select","Start"]
"ddtodr1" : ["Attack","Jump","Item","Select","Start"]
"ddtodu" : ["Attack","Jump","Item","Select","Start"]
"ddtodur1" : ["Attack","Jump","Item","Select","Start"]
"ddsom" : ["Attack","Jump","Select","Item","Start"]
"ddsoma" : ["Attack","Jump","Select","Item","Start"]
"ddsomar1" : ["Attack","Jump","Select","Item","Start"]
"ddsomb" : ["Attack","Jump","Select","Item","Start"]
"ddsomh" : ["Attack","Jump","Select","Item","Start"]
"ddsomj" : ["Attack","Jump","Select","Item","Start"]
"ddsomjr1" : ["Attack","Jump","Select","Item","Start"]
"ddsomjr2" : ["Attack","Jump","Select","Item","Start"]
"ddsomr1" : ["Attack","Jump","Select","Item","Start"]
"ddsomr2" : ["Attack","Jump","Select","Item","Start"]
"ddsomr3" : ["Attack","Jump","Select","Item","Start"]
"ddsomu" : ["Attack","Jump","Select","Item","Start"]
"ddsomur1" : ["Attack","Jump","Select","Item","Start"]
"ehrgeiz" : ["Weak Low Attack","Weak High Attack","Special Attack","Guard","Start"]
"ehrgeizja" : ["Weak Low Attack","Weak High Attack","Special Attack","Guard","Start"]
"ehrgeizua" : ["Weak Low Attack","Weak High Attack","Special Attack","Guard","Start"]
"daraku" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"kabukikl" : ["Weak Slash","Medium Slash","Weak Kick","Medium Kick","Start","Select"]
"fatfury1" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"fatfury2" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfursp" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfurspa" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfury3" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"fatfurwa" : ["Punch","Kick","Powerful Attack","Plane Switch","Start"]
"fightfev" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"fightfeva" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"fghthist" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthista" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistjb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistub" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fghthistuc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"karnovr" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start","Select"]
"fgtlayer" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fgtlayerj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"fvipers" : ["Punch","Kick","Guard","Start"]
"fvipersb" : ["Punch","Kick","Guard","Start"]
"ffight" : ["Attack","Jump","Start"]
"ffighta" : ["Attack","Jump","Start"]
"ffightj" : ["Attack","Jump","Start"]
"ffightj1" : ["Attack","Jump","Start"]
"ffightj2" : ["Attack","Jump","Start"]
"ffightj3" : ["Attack","Jump","Start"]
"ffightj4" : ["Attack","Jump","Start"]
"ffightu" : ["Attack","Jump","Start"]
"ffightu1" : ["Attack","Jump","Start"]
"ffightua" : ["Attack","Jump","Start"]
"ffightub" : ["Attack","Jump","Start"]
"ffightuc" : ["Attack","Jump","Start"]
"ffreveng" : ["Weak Punch","Strong Punch","Special","Weak Kick","Strong Kick","Taunt"]
"ffrevng10" : ["Weak Punch","Strong Punch","Special","Weak Kick","Strong Kick","Taunt"]
"fotns" : ["Weak Punch","Weak Kick","Hard Punch","Hard Kick","Boost","Taunt"]
"galaxyfg" : ["Weak Attack","Medium Attack","Strong Attack","Taunt","Start","Select"]
"garou" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"garouh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"garouha" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"garoup" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"ga2" : ["Attack","Jump","Magic","Start"]
"ga2j" : ["Attack","Jump","Magic","Start"]
"ga2u" : ["Attack","Jump","Magic","Start"]
"gaxeduel" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"groovef" : ["Weak Punch","Strong Punch","Overhead Attack","Weak Kick","Strong Kick","Dash Attack","Taunt"]
"ggx" : ["Punch","Kick","Slash","Hard Slash","Taunt"]
"ggx15" : ["Punch","Kick","Slash","Hard Slash","Start"]
"ggxx" : ["Punch","Kick","Slash","Hard Slash","Dust Attack","Taunt"]
"ggxxrl" : ["Punch","Kick","Slash","Hard Slash","Dust Attack","Taunt"]
"ggxxrlo" : ["Punch","Kick","Slash","Hard Slash","Dust Attack","Taunt"]
"ggxxsla" : ["Punch","Kick","Slash","Hard Slash","Dust Attack","Taunt"]
"ggxxac" : ["Punch","Kick","Slash","Hard Slash","Dust Attack","Taunt"]
"ggisuka" : ["Punch","Kick","Slash","Hard Slash","Furimuki"]
"hvnsgate" : ["Guard","Punch","Kick","Start"]
"holo" : ["Weak Attack","Strong Attack","Start"]
"hook" : ["Attack","Jump","Start"]
"hookj" : ["Attack","Jump","Start"]
"hooku" : ["Attack","Jump","Start"]
"hsf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hsf2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hsf2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"hsf2j1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"jchan" : ["Light Punch","Heavy Punch","Light Kick","Heavy Kick","Start"]
"jchana" : ["Light Punch","Heavy Punch","Light Kick","Heavy Kick","Start"]
"jchan2" : ["Light Punch","Heavy Punch","Light Kick","Heavy Kick","Taunt"]
"jojo" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoa" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoar1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoar2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoj" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojojr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojojr2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojon" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojonr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojonr2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojor1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojor2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojou" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojour1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojour2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoba" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobajr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobajr2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojoban" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobaner1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobaner2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobanr1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobanr2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobar1" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"jojobar2" : ["Light Attack","Medium Attack","Heavy Attack","Stand","Taunt"]
"kaiserkn" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"gblchmp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"kaiserknj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"dankuga" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"karatblz" : ["Jump","Attack","Start"]
"karatblza" : ["Jump","Attack","Start"]
"karatblzj" : ["Jump","Attack","Start"]
"karatblzt" : ["Jump","Attack","Start"]
"karatblzu" : ["Jump","Attack","Start"]
"kchamp" : ["Start"]
"kchampvs" : ["Start"]
"kchampvs2" : ["Start"]
"kchampvs3" : ["Start"]
"kchampvs4" : ["Start"]
"karatedo" : ["Start"]
"karatevs" : ["Start"]
"karatour" : ["Attack","Jump","Start"]
"karatourj" : ["Attack","Jump","Start"]
"kinst" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"kinst2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"kinst2uk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"killbld" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"killbld100" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"killbld104" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"killbld106" : ["Weak Slash","Weak Kick","Strong Slash","Strong Kick","Start"]
"kof94" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof95" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof95a" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof95h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof96" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof96h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start","Select"]
"kof97" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof97h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof97k" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98a" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98k" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98ka" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof98um" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof98umh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt"]
"kof99" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99e" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99k" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99ka" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof99p" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2000" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2000n" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2001" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2001h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2002" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2003" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kof2003h" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kf2k3pcb" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"kofxi" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Body Blow","Taunt"]
"kofnw" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Heat Mode","Taunt"]
"kofnwj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Heat Mode","Taunt"]
"kizuna" : ["Punch","Kick","Weapon Strike","Tag","Start","Select"]
"kizuna4p" : ["Punch","Kick","Weapon Strike","Tag","Start","Select"]
"knights" : ["Attack","Jump","Start"]
"knightsj" : ["Attack","Jump","Start"]
"knightsja" : ["Attack","Jump","Start"]
"knightsu" : ["Attack","Jump","Start"]
"kov" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov111" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov114" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov115" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kovplus" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kovplusa" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov2p" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov2p200" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov2p202" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov2p203" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kov2p204" : ["Attack","Jump","Open Item Menu","Use Item","Start"]
"kbash" : ["Attack","Jump","Start"]
"kbashk" : ["Attack","Jump","Start"]
"kbashp" : ["Attack","Jump","Start"]
"knckhead" : ["High Attack","Low Attack","Jump","Start"]
"knckheadj" : ["High Attack","Low Attack","Jump","Start"]
"knckheadjp" : ["High Attack","Low Attack","Jump","Start"]
"lastblad" : ["Weak Slash","Strong Slash","Weak Kick","Repel","Taunt","Select"]
"lastbladh" : ["Weak Slash","Strong Slash","Weak Kick","Repel","Taunt","Select"]
"lastsold" : ["Weak Slash","Strong Slash","Weak Kick","Repel","Taunt","Select"]
"lastbld2" : ["Weak Slash","Medium Slash","Weak Kick","Repel","Taunt","Select"]
"mace" : ["Quick Attack","Strong Attack","Kick","Evade","Start"]
"macea" : ["Quick Attack","Strong Attack","Kick","Evade","Start"]
"mtlchamp" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchamp1" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampa" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampj" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampu" : ["High Attack","Mid Attack","Low Attack","Start"]
"mtlchampu1" : ["High Attack","Mid Attack","Low Attack","Start"]
"martmast" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmast102c" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmast103c" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmast104c" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"martmasttw" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"msh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"msha" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshbr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Cycle Gems"]
"mshvsf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfa1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfb1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfj2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mshvsfu1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvsc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvsca" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvsch" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscjsing" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvscur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"mvsc2" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Variable Assist 1","Variable Assist 2","Taunt"]
"mvsc2u" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Variable Assist 1","Variable Assist 2","Taunt"]
"matrim" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"mslug" : ["Shot","Jump","Grenade","Not Used","Start","Select"]
"mslug2" : ["Shot","Jump","Grenade","Not Used","Start","Select"]
"mslugx" : ["Shot","Jump","Grenade","Not Used","Start","Select"]
"mslug3" : ["Shot","Jump","Grenade","Not Used","Start","Select"]
"mslug3a" : ["Shot","Jump","Grenade","Not Used","Start","Select"]
"mslug3h" : ["Shot","Jump","Grenade","Not Used","Start","Select"]
"mslug4" : ["Shot","Jump","Grenade","Vehicle Self-Destruct Attack","Start","Select"]
"mslug4h" : ["Shot","Jump","Grenade","Vehicle Self-Destruct Attack","Start","Select"]
"mslug5" : ["Shot","Jump","Grenade","Vehicle Self-Destruct Attack","Start","Select"]
"mslug5h" : ["Shot","Jump","Grenade","Vehicle Self-Destruct Attack","Start","Select"]
"ms5pcb" : ["Shot","Jump","Grenade","Vehicle Self-Destruct Attack","Start","Select"]
"mslug6" : ["Shot","Jump","Grenade","Vehicle Self-Destruct Attack","Switch Weapon","Start"]
"mk" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkla1" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkla2" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkla3" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkla4" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkprot4" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkprot8" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkprot9" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mkr4" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r30" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r31e" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r32e" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r11" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r14" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r20" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk2r21" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Start"]
"mk3" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk3r20" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk3p40" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk3r10" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk4" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk4a" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"mk4b" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"ngbc" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Tag Out","Taunt"]
"ngbcj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Tag Out","Taunt"]
"nwarr" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarra" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarrb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarrh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"nwarru" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntjr1s" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"vhuntjr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ninjamas" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start","Select"]
"plsmaswd" : ["Horizontal Attack","Vertical Attack","Kick","Movement","Taunt"]
"plsmaswda" : ["Horizontal Attack","Vertical Attack","Kick","Movement","Taunt"]
"stargld2" : ["Horizontal Attack","Vertical Attack","Kick","Movement","Taunt"]
"powerins" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"powerinsj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"powerinspj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"powerinspu" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"pwrinst2" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"pwrinst2a" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"pwrinst2j" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"plegends" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"plegendsj" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Start"]
"primrage" : ["High Quick","High Fierce","Low Quick","Low Fierce","Start"]
"primrage20" : ["High Quick","High Fierce","Low Quick","Low Fierce","Start"]
"primrageo" : ["High Quick","High Fierce","Low Quick","Low Fierce","Start"]
"primrag2" : ["High Quick","High Fierce","High Power","Low Quick","Low Fierce","Low Power","Taunt"]
"pjustic" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"pjustica" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"rotd" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"rotdh" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"ragnagrd" : ["Light Punch","Light Kick","Heavy Punch","Heavy Kick","Start","Select"]
"rdft2" : ["Fire","Bomb","Start"]
"rdft22kc" : ["Fire","Bomb","Start"]
"rdft2a" : ["Fire","Bomb","Start"]
"rdft2aa" : ["Fire","Bomb","Start"]
"rdft2it" : ["Fire","Bomb","Start"]
"rdft2j" : ["Fire","Bomb","Start"]
"rdft2ja" : ["Fire","Bomb","Start"]
"rdft2jb" : ["Fire","Bomb","Start"]
"rdft2jc" : ["Fire","Bomb","Start"]
"rdft2s" : ["Fire","Bomb","Start"]
"rdft2t" : ["Fire","Bomb","Start"]
"rdft2u" : ["Fire","Bomb","Start"]
"rdft2us" : ["Fire","Bomb","Start"]
"rfjet" : ["Fire","Bomb","Start"]
"rfjet2kc" : ["Fire","Bomb","Start"]
"rfjeta" : ["Fire","Bomb","Start"]
"rfjetj" : ["Fire","Bomb","Start"]
"rfjets" : ["Fire","Bomb","Start"]
"rfjetsa" : ["Fire","Bomb","Start"]
"rfjett" : ["Fire","Bomb","Start"]
"rfjetu" : ["Fire","Bomb","Start"]
"rbff1" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff1a" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff1k" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff1ka" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbffspec" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbffspeck" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff2" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff2h" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"rbff2k" : ["Punch","Kick","Powerful Attack","Plane Switch","Start","Select"]
"redearth" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"redearthn" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"redearthnr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"redearthr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"warzard" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"warzardr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Change Orb"]
"ringdest" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdesta" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdestb" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"ringdesth" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"smbomb" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"smbombr1" : ["Grab","Light Punch","Hard Punch","Light Kick","Hard Kick","Start"]
"rvschool" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"rvschoola" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"rvschoolu" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"jgakuen" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"jgakuen1" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Taunt"]
"rumblef" : ["Light Punch","Light Kick","Strong Punch","Strong Kick","Dodge","Taunt"]
"rumblefp" : ["Light Punch","Light Kick","Strong Punch","Strong Kick","Dodge","Taunt"]
"samsho" : ["Weak Slash","Medium Slash","Weak Kick","Medium Kick","Start","Select"]
"samshoh" : ["Weak Slash","Medium Slash","Weak Kick","Medium Kick","Start","Select"]
"samsho2" : ["Weak Slash","Medium Slash","Weak Kick","Medium Kick","Start","Select"]
"samsho2k" : ["Weak Slash","Medium Slash","Weak Kick","Medium Kick","Start","Select"]
"samsho2ka" : ["Weak Slash","Medium Slash","Weak Kick","Medium Kick","Start","Select"]
"samsho3" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"fswords" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho3h" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho4" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho4k" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Start","Select"]
"samsho5" : ["Weak Slash","Medium Slash","Kick","Meditation","Start","Select"]
"samsho5a" : ["Weak Slash","Medium Slash","Kick","Meditation","Start","Select"]
"samsho5h" : ["Weak Slash","Medium Slash","Kick","Meditation","Start","Select"]
"samsh5sp" : ["Weak Slash","Medium Slash","Kick","Meditation","Start","Select"]
"samsh5sph" : ["Weak Slash","Medium Slash","Kick","Meditation","Start","Select"]
"samsh5spho" : ["Weak Slash","Medium Slash","Kick","Meditation","Start","Select"]
"samsptk" : ["Weak Slash","Medium Slash","Strong Slash","Kick","Special","Taunt"]
"sams64" : ["Weak Attack","Strong Attack","Throw","3D Movement","Start"]
"sams64_2" : ["Weak Attack","Medium Attack","Strong Attack","3D Movement","Start"]
"slammast" : ["Attack","Jump","Start"]
"mbomberj" : ["Attack","Jump","Start"]
"slammastu" : ["Attack","Jump","Start"]
"mbombrd" : ["Grab","Attack","Jump","Start"]
"mbombrdj" : ["Grab","Attack","Jump","Start"]
"savagere" : ["Punch","Kick","Weapon Strike","Dimensional Attack","Start","Select"]
"svc" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"svcpcb" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"svcpcba" : ["Weak Punch","Weak Kick","Strong Punch","Strong Kick","Taunt","Select"]
"schamp" : ["Barrier","Punch","Kick","Start"]
"sfight" : ["Barrier","Punch","Kick","Start"]
"souledge" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgea" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgeja" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgeua" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"souledgeuc" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbr" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbra" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrab" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrja" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrjb" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrjc" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbrub" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"soulclbruc" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"svg" : ["Light Slash","Medium Slash","Heavy Slash","Kick","Taunt"]
"svghk" : ["Light Slash","Medium Slash","Heavy Slash","Kick","Taunt"]
"svgpcb" : ["Light Slash","Medium Slash","Heavy Slash","Kick","Taunt"]
"svgtw" : ["Light Slash","Medium Slash","Heavy Slash","Kick","Taunt"]
"starglad" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"stargladj" : ["Horizontal Attack","Vertical Attack","Kick","Guard","Start"]
"sf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfan" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfjan" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfw" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ea" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2eb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ed" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ee" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ef" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2em" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2en" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2j17" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2jl" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ub" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ud" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ue" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ug" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ui" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2uk" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2um" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ce" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceea" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceec" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceja" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2cejb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2cejc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2cet" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceua" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceub" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2ceuc" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2hf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2hfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sf2hfu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiia" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiih" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiij" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiin" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiina" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiiiu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii2n" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3n" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3nr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3r1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfiii3ur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfar2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfar3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfau" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfza" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzbr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzhr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzjr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzch" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfach" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfzbch" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa2u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa2ur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2b" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2br1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2n" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2al" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz2alr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3b" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3hr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3ur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfa3us" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3ar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3jr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfz3ugd" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"sfex" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexp" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexpj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexpj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfexpu1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2u1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2p" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2pa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2ph" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2pj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sfex2pu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftm" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftm110" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftm111" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftmj112" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftmj114" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sftmk112" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"s1945iii" : ["Fire","Bomb","Start"]
"s1945p" : ["Fire","Bomb","No Use","No Use","Start"]
"suikoenb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"sdodgeb" : ["Throw Ball","Pass","Jump","Fake","Start"]
"sgemf" : ["Punch","Kick","Special","Taunt"]
"sgemfa" : ["Punch","Kick","Special","Taunt"]
"sgemfh" : ["Punch","Kick","Special","Taunt"]
"pfghtj" : ["Punch","Kick","Special","Taunt"]
"ssf2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2a" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2ar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2h" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2j" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2jr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2jr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2r1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2u" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tba" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tbu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2t" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2ta" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2th" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2tur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2xj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2xjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssf2xjr1r" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"ssoldier" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"psoldier" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"survarts" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"survartsj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"survartsu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"tattass" : ["High Punch","Low Punch","Special","Block","High Kick","Low Kick","Start"]
"tattassa" : ["High Punch","Low Punch","Special","Block","High Kick","Low Kick","Start"]
"tekken" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekkenac" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekkenb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekkenjb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2a" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2b" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2jb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2jc" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2ua" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2ub" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken2ud" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3a" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3b" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3c" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3d" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3ja" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3je1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3ua" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tekken3ud" : ["Left Punch","Right Punch","Left Kick","Right Kick","Start"]
"tektagt" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtc1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtja" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtjb" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtjc1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtub" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"tektagtuc1" : ["Left Punch","Right Punch","Left Kick","Right Kick","Tag","Start"]
"timekill" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill100" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill120" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill121" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill121a" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill131" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"timekill132i" : ["Head","Back Arm","Front Arm","Back Leg","Front Leg","Start"]
"tophuntr" : ["Arm Stretch","Jump","Change Planes","Not Used","Start","Select"]
"tophuntrh" : ["Arm Stretch","Jump","Change Planes","Not Used","Start","Select"]
"tkdensho" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"tkdenshoa" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start"]
"umk3" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"umk3r10" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"umk3r11" : ["High Punch","Low Punch","Block","High Kick","Low Kick","Run","Start"]
"vsav" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsava" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsavu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vsav2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vhunt2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vhunt2r1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"vf" : ["Guard","Punch","Kick","Start"]
"vf2" : ["Guard","Punch","Kick","Start"]
"vf2a" : ["Guard","Punch","Kick","Start"]
"vf2b" : ["Guard","Punch","Kick","Start"]
"vf2o" : ["Guard","Punch","Kick","Start"]
"gowcaizr" : ["Quick Punch","Quick Kick","Strong Punch","Strong Kick","Start","Select"]
"wakuwak7" : ["Weak Punch","Strong Punch","Weak Kick","Strong Kick","Start","Select"]
"wargods" : ["High Punch","Low Punch","Guard","High Kick","Low Kick","3-D Button","Start"]
"wargodsa" : ["High Punch","Low Punch","Guard","High Kick","Low Kick","3-D Button","Start"]
"wargodsb" : ["High Punch","Low Punch","Guard","High Kick","Low Kick","3-D Button","Start"]
"wof" : ["Attack","Jump","Start"]
"wofa" : ["Attack","Jump","Start"]
"wofj" : ["Attack","Jump","Start"]
"wofr1" : ["Attack","Jump","Start"]
"wofu" : ["Attack","Jump","Start"]
"wofch" : ["Attack","Jump","Start"]
"wh1" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh1h" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh1ha" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh2" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh2h" : ["Punch","Kick","Throw","Not Used","Start","Select"]
"wh2j" : ["Punch","Kick","Taunt","Not Used","Start","Select"]
"whp" : ["Weak Punch","Medium Punch","Weak Kick","Medium Kick","Start","Select"]
"xmvsf" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfar2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfar3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfb" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfh" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfjr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfjr2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfjr3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfu" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfur1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmvsfur2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Taunt"]
"xmcota" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaa" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaar2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotab" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotah" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotahr1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj2" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotaj3" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotajr" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotar1" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
"xmcotau" : ["Weak Punch","Medium Punch","Strong Punch","Weak Kick","Medium Kick","Strong Kick","Start"]
})
