return ({
"m4tenten__r" : ""
"m4tenten__q" : ""
"m4tenten__p" : ""
"m4tenten__o" : ""
"m4tenten__n" : ""
"m4tenten__m" : ""
"m4tenten__l" : ""
"m4tenten__k" : ""
"m4tenten__z" : ""
"m4tenten__y" : ""
"m4tenten__x" : ""
"m4tenten__w" : ""
"m4tenten__v" : ""
"m4tenten__u" : ""
"m4tenten__t" : ""
"m4tenten__s" : ""
"m4tenten__b" : ""
"tenpindx" : "Up to 6-Player bowling game. Old-fashioned mechanisms replaced with 3-D projected pins, a video monitor for scores and attractions and electronic puck sensors."
"pepp0045c" : ""
"pepp0045b" : ""
"10yardj" : "It's 3rd and 10. The crowd is on its feet. Cheers fill the stadium. '36-88-24. Hut-hut-hut.' The ball is snapped. You grip the hard, cold, pigskin and the game is in your hands. You scramble left to avoid a flying tackle and look downfield. A receiver is open. You pump a forward pass. It's complete for a 10 yard gain and a first down.^^That's the rush the player gets with 10-YARD FIGHT, the 1- or 2-player video with the continuous play feature. The thrill of controlling the action. Of calling the plays and carrying the ball. Of a real Pro contest of America's # 1 Game.^^The player takes the field, takes the ball and takes on as much action as he can handle. He must score a touchdown in the time allotted to go from high school and college all the way to the Pros and the Super Bowl, with cheerleaders marking his progress-in-between.^^Each level begins with the player carrying the ball on the kick-off as far up the field as he can before getting tackled. Then he's in control as quarterback, running with the ball or going for a forwards pass or a lateral to a receiver who let's him know he's open by waving his arms. If the pass is intercepted a 20 yard penalty is called. As in authentic Pro ball, the clock is stopped when the player runs out of bounds. For bonus points after the referee signals a touchdown, the player can kick the ball or run with it to score 'points after'.^^10 YARD FIGHT^It lets YOU score like a Pro at the cashbox!"
"m4tenten__ay" : ""
"m4tenten__az" : ""
"m4tenten__j" : ""
"m4tenten__i" : ""
"m4tenten__h" : ""
"m4tenten__g" : ""
"m4tenten__f" : ""
"m4tenten__e" : ""
"m4tenten__d" : ""
"m4tenten__ar" : ""
"m4tenten__ao" : ""
"m4tenten__ap" : ""
"m4tenten__am" : ""
"m4tenten__an" : ""
"m4tenten__ak" : ""
"m4tenten__al" : ""
"m4tenten__ai" : ""
"m4tenten__aj" : ""
"m4tenten__ag" : ""
"m4tenten__ah" : ""
"m4tenten__ae" : ""
"m4tenten__af" : ""
"m4tenten__ac" : ""
"m4tenten__ad" : ""
"m4tenten__aa" : ""
"99lstwarb" : "Licensed from Sega. For more information about the game, please see the original Sega entry; 'Repulse'."
"99lstwark" : "Licensed from Sega. For more information about the game, please see the original Sega entry; 'Repulse'."
"1941r1" : "Export release. Game developed in Japan. For more information about the game itself, please see the original Japanese release entry; '1941 - Counter Attack [B-Board 89625B-1]'."
"pepp0046a" : ""
"pepp0046b" : ""
"005" : "Agent 005 brings new cash collections to you. His mission is to deliver secret attache cases to an awaiting helicopter. Through wily street chases and the shadows of warehouse darkness to slippery skating rink maneuvers and the blazing aerial getaway fight. Agent 005 steels the scene and delivers customers to you. Fun-filled music attracts them. Four thrilling escape scenes challenge them and the continuous fun keeps them playing and playing. The unique audio and video excitement matches every players skill level.^^And 005 is a RasterScan Convert, a Game which can later be converted to a brand new top earning game at a substantial savings.^^Put Agent 005 on your side and win the chase for higher profits. For more information on the latest in video-game action, call your nearest Sega/Gremlin distributor.^^The chase is on. Agent 005 makes away with an attache case. A hovering helicopter awaits his arrival, but first... Enemy guards pound the street in pursuit. 005 must duck into a new scene.^^Inside a warehouse. Avoid being caught in the guard's flashlight beams... once 005 is detected, the chase quickens to super fast. Blast the guards with stun-gas and score valuable points.^^Slip into a skate rink. And slip you will. There is no stopping on ice and the same goes for the thrills. Sliding and firing... firing and sliding. 005 can call his helicopter to escape.^^The final flight fight. High flying aerial excitement. 005 has reached his helicopter in all other scenes and now finds his high scoring, high soaring getaway copter in a new test balloon and parachute bombs close in from all sides. 005 blast away to score points and to escape. Then the final challenge is thrown at his skill - a blazing battle with the enemy copter. Win now and you win big.^^It's free-wheeling fun with fun-filled music and sound. Its stealth and pursuit is like no other video game. Everybody's after Agent 005. You should be, too. Call your nearest Sega/Gremlin distributor today and make sure 005 is on your side."
"pepp0083" : ""
"1941u" : "Export release. Game developed in Japan. For more information about the game itself, please see the original Japanese release entry; '1941 - Counter Attack [B-Board 89625B-1]'."
"1941" : "Export release. Game developed in Japan. For more information about the game itself, please see the original Japanese release entry; '1941 - Counter Attack [B-Board 89625B-1]'."
"19in1" : "Bootleg release. The games found in this release were made by several different companies, mostly from Japan.^^It includes the following games:^1. 'Defender'^2. 'Stargate'^3. 'Bubbles'^4. 'Joust'^5. 'Robotron: 2084'^6. 'Blaster'^7. 'Splat!'^8. 'Rally-X'^9. 'Battle City'^10. 'Mario Bros.'^11. 'New Rally-X'^12. 'Ghosts'n Goblins'^13. 'Solomon's Key'^14. 'Gradius'^15. 'Sky Kid'^16. 'Ice Climber'^17. 'Super Mario Bros.'^18. 'Do! Run Run'^19. 'Kick Rider'"
"18w2" : "NEW: 18 WHEELER^Electro-Mechanical Game Excitement by Midway - a Bally Company.^^KING OF THE ROAD!"
"pepp0042a" : "Video Poker game."
"m4tenten__2" : ""
"m4tenten__1" : ""
"m4tenten__0" : ""
"18w" : "NEW: 18 WHEELER^Electro-Mechanical Game Excitement by Midway - a Bally Company.^^KING OF THE ROAD!"
"18wheelrt" : "EXPLOSIVE DRIVING! ROAD MONSTER!^Drive a humungous 18 Wheeler! Crush! Destroy! A no-holds barred driving battle!^^Squeeze through the traffic! Side by Side! Emergency brake! Falling cargo! Race across the wide American continent, obstructing your rival all the way!^^Incredible graphics brought to you by the power of NAOMI. Real 18 Wheeler action. control sensation and traffic conditions have been accurately recreated as far as possible. Carefully and quickly deliver your cargo. Brand new, original gameplay offers fun and excitement for a wide range of players. Adds life to any location, while generating a consistently high income.^^Drive your rig across America, from New York to San Francisco.^* 4 rigs to choose from, each with differing levels of speed, torque and toughness. Competing against your rival, deliver your cargo safely to your destination within the time limit. The quicker you get there, the bigger your reward.^* 4 stages in all. Clear each stage to access the bonus stage, where you can test your parking skills and earn bonus items, like the horn muffler and a new engine!^* Eye-catching cabinet design, evoking a real tough trucker feeling.^* Equipped with a real sized 48cm diameter steering wheel, to accurately convey that Big-Rig feeling.^* Experience the Raw power and noise of a 14000cc engine, with a sub-woofer and base shaker located under the seat.^* Two Person bench seat with a horn located on the passenger side - ideal for couples to enjoy!^* 50 inch monitor to convey all of the in-your-face excitement!^* 2 stage Transmission Change lever.^* Horn button"
"18wheelro" : "EXPLOSIVE DRIVING! ROAD MONSTER!^Drive a humungous 18 Wheeler! Crush! Destroy! A no-holds barred driving battle!^^Squeeze through the traffic! Side by Side! Emergency brake! Falling cargo! Race across the wide American continent, obstructing your rival all the way!^^Incredible graphics brought to you by the power of NAOMI. Real 18 Wheeler action. control sensation and traffic conditions have been accurately recreated as far as possible. Carefully and quickly deliver your cargo. Brand new, original gameplay offers fun and excitement for a wide range of players. Adds life to any location, while generating a consistently high income.^^Drive your rig across America, from New York to San Francisco.^* 4 rigs to choose from, each with differing levels of speed, torque and toughness. Competing against your rival, deliver your cargo safely to your destination within the time limit. The quicker you get there, the bigger your reward.^* 4 stages in all. Clear each stage to access the bonus stage, where you can test your parking skills and earn bonus items, like the horn muffler and a new engine!^* Eye-catching cabinet design, evoking a real tough trucker feeling.^* Equipped with a real sized 48cm diameter steering wheel, to accurately convey that Big-Rig feeling.^* Experience the Raw power and noise of a 14000cc engine, with a sub-woofer and base shaker located under the seat.^* Two Person bench seat with a horn located on the passenger side - ideal for couples to enjoy!^* 50 inch monitor to convey all of the in-your-face excitement!^* 2 stage Transmission Change lever.^* Horn button"
"m4tenten__ax" : ""
"pepp0063" : ""
"18wheels" : "EXPLOSIVE DRIVING! ROAD MONSTER!^Drive a humungous 18 Wheeler! Crush! Destroy! A no-holds barred driving battle!^^Squeeze through the traffic! Side by Side! Emergency brake! Falling cargo! Race across the wide American continent, obstructing your rival all the way!^^Incredible graphics brought to you by the power of NAOMI. Real 18 Wheeler action. control sensation and traffic conditions have been accurately recreated as far as possible. Carefully and quickly deliver your cargo. Brand new, original gameplay offers fun and excitement for a wide range of players. Adds life to any location, while generating a consistently high income.^^Drive your rig across America, from New York to San Francisco.^* 4 rigs to choose from, each with differing levels of speed, torque and toughness. Competing against your rival, deliver your cargo safely to your destination within the time limit. The quicker you get there, the bigger your reward.^* 4 stages in all. Clear each stage to access the bonus stage, where you can test your parking skills and earn bonus items, like the horn muffler and a new engine!^* Eye-catching cabinet design, evoking a real tough trucker feeling.^* Equipped with a real sized 48cm diameter steering wheel, to accurately convey that Big-Rig feeling.^* Experience the Raw power and noise of a 14000cc engine, with a sub-woofer and base shaker located under the seat.^* Two Person bench seat with a horn located on the passenger side - ideal for couples to enjoy!^* 50 inch monitor to convey all of the in-your-face excitement!^* 2 stage Transmission Change lever.^* Horn button"
"tgoldeye" : ""
"m4tenten__8" : ""
"m4tenten__7" : ""
"m4tenten__6" : ""
"m4tenten__5" : ""
"m4tenten__4" : ""
"m4tenten__3" : ""
"m4tenten__aw" : ""
"pepp0043b" : ""
"pekoc801" : ""
"progolf" : "This standalone PCB re-edition version was originally released as a DECO Cassette for the DECO Cassette System. For more information about the game itself, please see the Deco Cassette entry; 'Tournament Pro Golf [Model DT-113]'."
"88games" : "Export release. Game developed in Japan by Konami. For more information, please see the original Japanese release entry: 'Hyper Sports Special [Model GX861]'."
"cprogolf18" : "An updated version of 'Tournament Pro Golf [DT-113]'."
"ie15" : "Russian monochrome computer."
"15lions" : ""
"hazl1420" : ""
"1392apvs" : "Similar to the '1292 Advanced Programmable Video System'."
"1941j" : "A vertically scrolling shoot'em up."
"pepp0562" : ""
"shmc1200" : "An Australian clone of the RCA Studio II."
"pepp0045a" : ""
"m4tenten__a1" : ""
"m4tenten__a2" : ""
"10yard85" : "North American Release, licensed to Taito America Corp. Game developed in Japan by Irem. For more information, please see the original Japanese entry."
"m4tenten__a0" : ""
"10yard" : "Export version. Game developed in Japan by Irem Corp. For more information please see the original Japanese entry."
"pex0046p" : ""
"99lstwar" : "Licensed from Sega. For more information about the game, please see the original Sega entry; 'Repulse'."
"progolfa" : "This standalone PCB re-edition version was originally released as a DECO Cassette for the DECO Cassette System. For more information about the game itself, please see the Deco Cassette entry; 'Tournament Pro Golf [Model DT-113]'."
"1292apvs" : ""
"pepp0046" : ""
"pepp0045d" : ""
"100lions" : "A video slot machine with 5 reels and 100 lines."
"pepp0045" : ""
"pepp0043a" : ""
"pepp0043" : ""
"pepp0042" : "Video Poker game."
"flagrall" : "Korean game."
"pex0042p" : "Video Poker game."
"pepp0023" : ""
"18wheelu" : "EXPLOSIVE DRIVING! ROAD MONSTER!^Drive a humungous 18 Wheeler! Crush! Destroy! A no-holds barred driving battle!^^Squeeze through the traffic! Side by Side! Emergency brake! Falling cargo! Race across the wide American continent, obstructing your rival all the way!^^Incredible graphics brought to you by the power of NAOMI. Real 18 Wheeler action. control sensation and traffic conditions have been accurately recreated as far as possible. Carefully and quickly deliver your cargo. Brand new, original gameplay offers fun and excitement for a wide range of players. Adds life to any location, while generating a consistently high income.^^Drive your rig across America, from New York to San Francisco.^* 4 rigs to choose from, each with differing levels of speed, torque and toughness. Competing against your rival, deliver your cargo safely to your destination within the time limit. The quicker you get there, the bigger your reward.^* 4 stages in all. Clear each stage to access the bonus stage, where you can test your parking skills and earn bonus items, like the horn muffler and a new engine!^* Eye-catching cabinet design, evoking a real tough trucker feeling.^* Equipped with a real sized 48cm diameter steering wheel, to accurately convey that Big-Rig feeling.^* Experience the Raw power and noise of a 14000cc engine, with a sub-woofer and base shaker located under the seat.^* Two Person bench seat with a horn located on the passenger side - ideal for couples to enjoy!^* 50 inch monitor to convey all of the in-your-face excitement!^* 2 stage Transmission Change lever.^* Horn button"
"18wheelr" : "EXPLOSIVE DRIVING! ROAD MONSTER!^Drive a humungous 18 Wheeler! Crush! Destroy! A no-holds barred driving battle!^^Squeeze through the traffic! Side by Side! Emergency brake! Falling cargo! Race across the wide American continent, obstructing your rival all the way!^^Incredible graphics brought to you by the power of NAOMI. Real 18 Wheeler action. control sensation and traffic conditions have been accurately recreated as far as possible. Carefully and quickly deliver your cargo. Brand new, original gameplay offers fun and excitement for a wide range of players. Adds life to any location, while generating a consistently high income.^^Drive your rig across America, from New York to San Francisco.^* 4 rigs to choose from, each with differing levels of speed, torque and toughness. Competing against your rival, deliver your cargo safely to your destination within the time limit. The quicker you get there, the bigger your reward.^* 4 stages in all. Clear each stage to access the bonus stage, where you can test your parking skills and earn bonus items, like the horn muffler and a new engine!^* Eye-catching cabinet design, evoking a real tough trucker feeling.^* Equipped with a real sized 48cm diameter steering wheel, to accurately convey that Big-Rig feeling.^* Experience the Raw power and noise of a 14000cc engine, with a sub-woofer and base shaker located under the seat.^* Two Person bench seat with a horn located on the passenger side - ideal for couples to enjoy!^* 50 inch monitor to convey all of the in-your-face excitement!^* 2 stage Transmission Change lever.^* Horn button"
"m4tenten" : ""
"m4tenten__av" : ""
"m4tenten__au" : ""
"m4tenten__at" : ""
"m4tenten__as" : ""
"m4tenten__aq" : ""
"1on1gov" : "A fun one or two players basketball game.^^You play one on one street basketball, must using your skills on the court like guard move, dribbling and dunks but including some illegal tactics such as punches and kicks but no foul, is just compete and win the game no matter how!"
"pex0045p" : ""
"m4tenten__a" : ""
"99lstwara" : "Licensed from Sega. For more information about the game, please see the original Sega entry; 'Repulse'."
"m4tenten__ab" : ""
"m4tenten__c" : ""
"m4tenten__9" : ""
})
