return(
   {
      "prefs" : {
         "imgpath" : "help_images/"
         "l1" : []
         "l0" : []
         "driveletters" : 
         "getout" : false
         "a0" : []
         "defaults" : 
         "imgext" : ".jpg"
         "gl0" : []
      }
      "updatechecking" : false
      "req" : {
         "textentr" : -6
         "slideint" : -9
         "filereqs" : -3
         "huevalue" : -8
         "liner" : -100
         "rgbvalue" : -7
         "executef" : -2
         "exenoret" : -5
         "keyboard" : -1
         "menusort" : -4
      }
      "tsc" : 1
      "frost_freezecount" : 0
      "bgs_freezecount" : 0
      "vernum" : 162
      "version" : "16.2"
      "songdir" : ""
      "romlistfolder" : "/Volumes/attractfolder/attractfolder/romlists/"
      "emulatordata" : {}
      "LNG" : "EN"
      "dat_freezecount" : 0
      "folder" : "/Volumes/attractfolder/attractfolder/layouts/Arcadeflow/"
      "bar" : {
         "pic" : 
         "time0" : 0
         "time1" : 0
         "scroller" : ["O-------","-O------","--O-----","---O----","----O---","-----O--","------O-","-------O","------O-","-----O--","----O---","---O----","--O-----","-O------"]
         "progress" : 0
         "stop" : "stop"
         "start" : "start"
         "picbg" : 
         "size" : 300
         "darkalpha" : 90
         "splashmessage" : ""
         "dark" : 60
         "count" : 0
         "text" : 
         "bg" : 
      }
      "scrape" : {
         "regionprefs" : []
         "checktable" : {}
         "forcemedia" : false
         "listoflists" : 
         "totalroms" : 0
         "inprf" : {}
         "quit" : false
         "separator2" : "============================================================"
         "separator1" : "------------------------------------------------------------"
         "threads" : 0
         "romlist" : ""
         "report" : {}
         "requests" : ""
         "purgedromdirlist" : 
         "timeoutroms" : []
         "emudata" : 
         "scrapelist_lines" : 
         "dispatchid" : 0
         "onegame" : ""
         "columns" : 60
         "doneroms" : 0
         "scrapelist_file" : 
         "regiontable" : ["wor","us","eu","ss","jp"]
         "romlist_file" : 
         "stack" : []
         "romlist_lines" : 
      }
      "messageoverlay" : 
      "dat_freeze" : true
      "boxmessage" : [""]
      "subfolder" : "layouts/Arcadeflow/"
      "soundvolume" : 0
      "config" : {
         "exitcommand" : ""
         "header" : ["# Generated by Attract-Mode Plus v3.0.3","#"]
         "displays" : [{
            "filters" : ["	filter               All","	filter               Starred","		rule                 Favourite equals 1","	filter               Shooter","		rule                 Category contains Shooter","	filter               Platform","		rule                 Category contains Platform","	filter               "Fighter VS"","		rule                 Category contains Fighter","		rule                 Category contains Versus","	filter               Fighter","		rule                 Category contains Fighter","		rule                 Category not_contains Versus","	filter               Driving","		rule                 Category contains Driving","	filter               Puzzle","		rule                 Category contains Puzzle","	filter               Sports","		rule                 Category contains Sports","	filter               Playlist","		rule                 Tags contains PLAYLIST","	filter               "Not Working"","		rule                 Status equals preliminary","	filter               "Vecchie Glorie"","		rule                 Tags contains Vecchie Glorie","	filter               "No Clones"","		rule                 CloneOf not_equals .*"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "BasicNEW"
            "display" : "mame"
            "romlist" : "mame"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1","	filter               "No Clones"","		rule                 CloneOf not_equals .*"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Amiga"
            "romlist" : "Amiga"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1","	filter               "No Clones"","		rule                 CloneOf not_equals .*"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Game Boy"
            "romlist" : "Game Boy"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Game Boy Advance"
            "romlist" : "Game Boy Advance"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Game Boy Color"
            "romlist" : "Game Boy Color"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Game Gear"
            "romlist" : "Game Gear"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Lynx"
            "romlist" : "Lynx"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Consoles"
            "romlist" : "Consoles"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Arcades"
            "romlist" : "Arcades"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Megadrive"
            "romlist" : "Megadrive"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Neo Geo Pocket"
            "romlist" : "Neo Geo Pocket"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Neo Geo Pocket Color"
            "romlist" : "Neo Geo Pocket Color"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Nintendo Wii"
            "romlist" : "Nintendo Wii"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "PC Engine"
            "romlist" : "PC Engine"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Sega MasterSystem"
            "romlist" : "Sega MasterSystem"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Super Nintendo Entertainment System"
            "romlist" : "Super Nintendo Entertainment System"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Vectrex"
            "romlist" : "Vectrex"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "WonderSwan"
            "romlist" : "WonderSwan"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "WonderSwan Color"
            "romlist" : "WonderSwan Color"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "msx"
            "romlist" : "msx"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Atari 2600"
            "romlist" : "Atari 2600"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Nintendo Entertainment System"
            "romlist" : "Nintendo Entertainment System"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "MSX 2"
            "romlist" : "msx2"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega32x"
            "romlist" : "sega32x"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Supergrafx"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "neogeo"
            "romlist" : "neogeo"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Atari 5200"
            "romlist" : "Atari 5200"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Atari 7800"
            "romlist" : "Atari 7800"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Coleco Vision"
            "romlist" : "Coleco Vision"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Odyssey 2"
            "romlist" : "Odissey 2"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Sega SG-1000"
            "romlist" : "Sega SG-1000"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ZX Spectrum"
            "romlist" : "ZX Spectrum"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Amstrad CPC"
            "romlist" : "Amstrad CPC"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "X68000"
            "romlist" : "X68000"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "X1"
            "romlist" : "X1"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "fbneo"
            "romlist" : "fbneo"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "PC Engine CD"
            "romlist" : "PC Engine CD"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Sega MEGA CD"
            "romlist" : "Sega MEGA CD"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Cave"
            "romlist" : "Cave"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "3DO"
            "romlist" : "3DO"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "c64"
            "romlist" : "Commodore 64"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Playstation"
            "romlist" : "Playstation"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Nec PC-98"
            "romlist" : "Nec PC-98"
         }
         ,{
            "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "surfacelayout"
            "display" : "AmigaX"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "archimedes"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "bbc micro"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "electron"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "amstrad gx4000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "apple 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "apple 2gs"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "aquarius"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari8bit"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari 400"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari 800"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari jaguar"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari st"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atomiswave"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cps1"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cps2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cps3"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "capcom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cave cv1000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cave 68000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "coleco adam"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "commodore 128"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "amiga 1200"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "amiga cd32"
            "romlist" : "Amiga CD32"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "commodore vic20"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "daphne"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "channel f"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "fm towns"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ibm pc"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "intellivision"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "mac os"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "macintosh"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "odyssey"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "windows"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ms dos"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "msx turbo r"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "namco"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec pc engine duo"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec pc engine gt"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec pc-88"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec pc-fx"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec turbo duo"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec turbo express"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nec turbografx-16"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "TurboGrafx CD"
            "romlist" : "TurboGrafx CD"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "neo geo cd"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "neo geo mvs"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "3ds"
            "romlist" : "3ds"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo 64"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo ds"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo dsi"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo famicom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo famicom disk system"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo game and watch"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo game boy light"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo game boy micro"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo game boy pocket"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo gamecube"
            "romlist" : "Game Cube"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo snes eu"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo super famicom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo switch"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo virtualboy"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo vs system"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo wii u"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "openbor"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pc"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "playstation 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "playstation 3"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "psp"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sam coupe"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "scummvm"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega cd"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "dreamcast"
            "romlist" : "Dreamcast"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "genesis"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "genesis 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega hikaru"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "master system 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "megadrive 32x"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "megadrive japan"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "model 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "model 3"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "naomi"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "naomi gd-rom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "saturn"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "saturn japan"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sc 3000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "stv"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "steam"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "taito type x"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "taito"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "tiger"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "videopac"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "xbox 360"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "xbox one"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "xbox"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega mark iii"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "marty"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "zx 81"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cdtv"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "dragon 32"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "swancrystal"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "trs-80"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "zx spectrum 3"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari falcon"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "plus4"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "hbmame"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nesicaxlive"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "n64dd"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ps4"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ps5"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "psvita"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "satellaview"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sinclair ql"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "spectravideo"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ti99"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "acorn atom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "enterprise"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "fm7"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "linux"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "oric"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pinball arcade"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pinball fx2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "thomson"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "trs80 coco"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "zaccaria pinball"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "visual pinball"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pinball fx3"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "future pinball"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "coregrafx ii"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "coregrafx"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "mega drive 2 japan"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "mega drive ii"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "triforce"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "ultra 64"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Atari XEGS"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Apple IIc"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Super 32X"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Lynx 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "super game boy"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "gba sp"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pet"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "c16"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "jaguar cd"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "videopac plus"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "cdi"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "ArtworkFX"
            "display" : "naomi 2"
            "romlist" : "naomi2"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "naomi 2 gd-rom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega system sp"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "williams"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "konami"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "midway"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "snk"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "atari"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "data east"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "socrates"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "supervision"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "adventure vision"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "arcadia 2001"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "apf mp1000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "mega duck"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "game.com"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "astrocade"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "microvision"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "wiiware"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "lcd game"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "gp32"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "game master"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "Playstation 2"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo super system"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nintendo playchoice"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega mega tech"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sega mega play"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "super nes new-style"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "super famicom jr"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nes new-style"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "new famicom"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pc engine lt"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "arcade"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "camputers lynx"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "colour genie"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "exl100"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "jupiter ace"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "mikrosha"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "nabu"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pacom 64"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "pegasus"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "sol-20"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "vg5000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "windows 3.11"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "windows 95"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "casio loopy"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "casio pv-1000"
            "romlist" : "Supergrafx"
         }
         ,{
            "filters" : []
            "in_menu" : "yes"
            "in_cycle" : "yes"
            "layout" : "Arcadeflow"
            "display" : "casio pv-2000"
            "romlist" : "Supergrafx"
         }
         ]
         "collections" : false
         "footer" : ["sound","	sound_volume         20","	ambient_volume       100","	movie_volume         20","","input_map","	edit_game            Escape+Down","	edit_game            Joy0 Down+Joy0 Button1","	left                 Left","	left                 Joy0 Left","	select               Return","	select               LControl","	select               Joy0 Button0","	custom2              X","	custom6              D","	filters_menu         F","	screenshot           P","	custom3              C","	prev_game            Q","	next_game            W","	prev_page            E","	prev_display         K","	next_display         L","	displays_menu        J","	prev_filter          G","	next_filter          H","	toggle_rotate_right  RBracket","	toggle_rotate_left   LBracket","	random_game          M","	add_favourite        Escape+LControl","	add_favourite        Joy0 Button0+Joy0 Button1","	add_favourite        V","	prev_favourite       B","	next_favourite       N","	add_tags             T","	prev_letter          Y","	next_letter          U","	layout_options       O","	custom4              A","	custom5              S","	next_page            R","	right                Joy0 Right","	right                Right","	custom1              Z","	back                 Escape","	back                 Joy0 Button1","	back                 Mouse RightButton","	up                   Up","	up                   Joy0 Up","	down                 Down","	down                 Joy0 Down","	configure            Tab","	configure            Joy0 Button4","	default             back	exit","	default             up	prev_game","	default             down	next_game","	default             left	prev_display","	default             right	next_display","","general","	language             en","	exit_command","	exit_message","	ui_font_size","	screen_saver_timeout 0","	displays_menu_exit   no","	hide_brackets        no","	group_clones         no","	startup_mode         default","	confirm_favourites   yes","	confirm_exit         yes","	mouse_threshold      10","	joystick_threshold   75","	window_mode          window","	screen_rotation      none","	filter_wrap_mode     default","	track_usage          yes","	multiple_monitors    no","	smooth_images        yes","	selection_max_step   128","	selection_speed_ms   40","	move_mouse_on_launch no","	scrape_snaps         yes","	scrape_marquees      yes","	scrape_flyers        yes","	scrape_wheels        yes","	scrape_fanart        no","	scrape_videos        no","	scrape_overview      yes","	thegamesdb_key","	power_saving         no","	video_decoder        software","	menu_prompt          Displays Menu","	menu_layout","	image_cache_mbytes   0","","saver_config","	param                basic_movie Yes","	param                blank_start_cmd","	param                blank_stop_cmd","	param                blank_time 120","	param                image_collage Yes","	param                movie_collage Yes","	param                overlay_art wheel","	param                preserve_ar No","	param                rgb_movie Yes","	param                sound Yes","","","plugin	History.dat","	enabled              no","	param                button H","	param                dat_path $HOME/history.dat","	param                generate_index","	param                index_clones No","	param                rows 30","","plugin	FPSMonitor","	enabled              no","	param                graph_size Small","	param                on_off Disabled","	param                reload Disabled","","plugin	KeyboardSearch","	enabled              yes","	param                results_mode Show Results","	param                trigger Custom1"]
      }
      "bgsongs" : []
      "zmenu_freezecount" : 0
      "emulatorsfolder" : "/Volumes/attractfolder/attractfolder/emulators/"
   }
)
