return(
{
  "prefs" : {
    "imgpath" : "help_images/"
    "l1" : []
    "l0" : []
    "driveletters" : 
    "getout" : false
    "a0" : []
    "defaults" : 
    "imgext" : ".jpg"
    "gl0" : []
  }
  "updatechecking" : false
  "req" : {
    "textentr" : -6
    "slideint" : -9
    "filereqs" : -3
    "huevalue" : -8
    "liner" : -100
    "rgbvalue" : -7
    "executef" : -2
    "exenoret" : -5
    "keyboard" : -1
    "menusort" : -4
  }
  "tsc" : 1
  "frost_freezecount" : 0
  "bgs_freezecount" : 0
  "vernum" : 162
  "version" : "16.2"
  "songdir" : ""
  "romlistfolder" : "/home/plex/attractfolder/romlists/"
  "emulatordata" : {}
  "LNG" : "EN"
  "dat_freezecount" : 0
  "folder" : "/home/plex/attractfolder/layouts/Arcadeflow/"
  "bar" : {
    "pic" : 
    "time0" : 0
    "time1" : 0
    "scroller" : ["O-------","-O------","--O-----","---O----","----O---","-----O--","------O-","-------O","------O-","-----O--","----O---","---O----","--O-----","-O------"]
    "progress" : 0
    "stop" : "stop"
    "start" : "start"
    "picbg" : 
    "size" : 300
    "darkalpha" : 90
    "splashmessage" : ""
    "dark" : 60
    "count" : 0
    "text" : 
    "bg" : 
  }
  "scrape" : {
    "regionprefs" : []
    "checktable" : {}
    "forcemedia" : false
    "listoflists" : 
    "totalroms" : 0
    "inprf" : {}
    "quit" : false
    "separator2" : "============================================================"
    "separator1" : "------------------------------------------------------------"
    "threads" : 0
    "romlist" : ""
    "report" : {}
    "requests" : ""
    "purgedromdirlist" : 
    "timeoutroms" : []
    "emudata" : 
    "scrapelist_lines" : 
    "dispatchid" : 0
    "onegame" : ""
    "columns" : 60
    "doneroms" : 0
    "scrapelist_file" : 
    "regiontable" : ["wor","us","eu","ss","jp"]
    "romlist_file" : 
    "stack" : []
    "romlist_lines" : 
  }
  "messageoverlay" : 
  "dat_freeze" : true
  "boxmessage" : [""]
  "subfolder" : "layouts/Arcadeflow/"
  "soundvolume" : 0
  "config" : {
    "exitcommand" : ""
    "header" : ["# Generated by Attract-Mode Plus v3.0.0","#"]
    "displays" : [{
      "filters" : ["	filter               All","	filter               Starred","		rule                 Favourite equals 1","	filter               Shooter","		rule                 Category contains Shooter","	filter               Platform","		rule                 Category contains Platform","	filter               "Fighter VS"","		rule                 Category contains Fighter","		rule                 Category contains Versus","	filter               Fighter","		rule                 Category contains Fighter","		rule                 Category not_contains Versus","	filter               Driving","		rule                 Category contains Driving","	filter               Puzzle","		rule                 Category contains Puzzle","	filter               Sports","		rule                 Category contains Sports","	filter               Playlist","		rule                 Tags contains PLAYLIST","	filter               "Not Working"","		rule                 Status equals preliminary","	filter               "Vecchie Glorie"","		rule                 Tags contains Vecchie Glorie"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "mame"
      "romlist" : "mame"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Sony Playstation 2"
      "romlist" : "Sony Playstation 2"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Amiga"
      "romlist" : "Amiga"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Game Boy"
      "romlist" : "Game Boy"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Game Boy Advance"
      "romlist" : "Game Boy Advance"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Game Boy Color"
      "romlist" : "Game Boy Color"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Game Gear"
      "romlist" : "Game Gear"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Lynx"
      "romlist" : "Lynx"
    }
    ,{
      "filters" : ["	filter               All","		sort_by              Name","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "letters"
      "display" : "Genesis"
      "romlist" : "Megadrive"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Neo Geo Pocket"
      "romlist" : "Neo Geo Pocket"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Neo Geo Pocket Color"
      "romlist" : "Neo Geo Pocket Color"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Nintendo Wii"
      "romlist" : "Nintendo Wii"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "PC Engine"
      "romlist" : "PC Engine"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Sega MasterSystem"
      "romlist" : "Sega MasterSystem"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Super Nintendo Entertainment System"
      "romlist" : "Super_Nintendo"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Vectrex"
      "romlist" : "Vectrex"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "WonderSwan"
      "romlist" : "WonderSwan"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "WonderSwan Color"
      "romlist" : "WonderSwan Color"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "msx"
      "romlist" : "msx"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Atari 2600"
      "romlist" : "Atari 2600"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Nintendo NES"
      "romlist" : "Nintendo NES"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "msx2"
      "romlist" : "msx2"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "sega32x"
      "romlist" : "sega32x"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Supergrafx"
      "romlist" : "Supergrafx"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "neogeo"
      "romlist" : "neogeo"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Atari 5200"
      "romlist" : "Atari 5200"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Atari 7800"
      "romlist" : "Atari 7800"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Coleco Vision"
      "romlist" : "Coleco Vision"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Odyssey 2"
      "romlist" : "Odissey 2"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Sega SG-1000"
      "romlist" : "Sega SG-1000"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "ZX Spectrum"
      "romlist" : "ZX Spectrum"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Amstrad CPC"
      "romlist" : "Amstrad CPC"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "X68000"
      "romlist" : "X68000"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "dirksimple"
      "romlist" : "Supergrafx"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "irem"
      "romlist" : "Supergrafx"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "konami"
      "romlist" : "Supergrafx"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "windows"
      "romlist" : "Windows"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "Playstation 2"
      "romlist" : "Playstation 2"
    }
    ,{
      "filters" : ["	filter               All","	filter               Favourites","		rule                 Favourite equals 1"]
      "in_menu" : "yes"
      "in_cycle" : "yes"
      "layout" : "Arcadeflow"
      "display" : "ALL GAMES COLLECTION"
      "romlist" : "Playstation 2"
    }
    ]
    "collections" : false
    "footer" : ["sound","	sound_volume         100","	ambient_volume       100","	movie_volume         100","","input_map","	configure            Tab","	prev_letter          LControl+Up","	next_letter          LControl+Down","	next_filter          LControl+Right","	configure            Escape+Up","	edit_game            Escape+Down","	prev_letter          Joy0 Up+Joy0 Button0","	next_letter          Joy0 Down+Joy0 Button0","	next_filter          Joy0 Right+Joy0 Button0","	configure            Joy0 Up+Joy0 Button1","	edit_game            Joy0 Down+Joy0 Button1","	back                 Escape","	back                 Joy0 Button1","	up                   Up","	up                   Joy0 Up","	down                 Down","	down                 Joy0 Down","	left                 Left","	left                 Joy0 Left","	right                Right","	right                Joy0 Right","	select               Return","	select               LControl","	select               Joy0 Button0","	custom1              Z","	prev_game            Q","	next_game            W","	prev_page            E","	next_page            R","	prev_display         Y","	next_display         U","	displays_menu        J","	filters_menu         F","	screenshot           P","	add_tags             T","	layout_options       O","	custom2              X","	custom3              C","	custom4              A","	custom5              S","	custom6              D","	add_favourite        Escape+LControl","	add_favourite        Joy0 Button0+Joy0 Button1","	add_favourite        K","	toggle_rotate_right  Equal","	toggle_rotate_right  Dash","	default             back	exit","	default             up	prev_game","	default             down	next_game","	default             left	prev_display","	default             right	next_display","","general","	language             en","	exit_command","	exit_message","	default_font         Barlow","	font_path","	ui_font_size","	screen_saver_timeout 0","	displays_menu_exit   no","	hide_brackets        no","	group_clones         no","	startup_mode         default","	confirm_favourites   no","	confirm_exit         yes","	mouse_threshold      10","	joystick_threshold   75","	window_mode          window","	screen_rotation      none","	filter_wrap_mode     default","	track_usage          yes","	multiple_monitors    no","	smooth_images        yes","	selection_max_step   128","	selection_speed_ms   40","	move_mouse_on_launch yes","	scrape_snaps         yes","	scrape_marquees      yes","	scrape_flyers        yes","	scrape_wheels        yes","	scrape_fanart        no","	scrape_videos        no","	scrape_overview      yes","	thegamesdb_key","	power_saving         no","	video_decoder        software","	menu_prompt          Displays Menu","	menu_layout","	image_cache_mbytes   0","","saver_config","	param                basic_movie Yes","	param                blank_start_cmd","	param                blank_stop_cmd","	param                blank_time 120","	param                image_collage Yes","	param                movie_collage Yes","	param                overlay_art wheel","	param                preserve_ar No","	param                rgb_movie Yes","	param                sound Yes","","intro_config","	param                detect_aspect Yes","	param                layout_rotation none","	param                play_intro No",""]
  }
  "bgsongs" : []
  "zmenu_freezecount" : 0
  "emulatorsfolder" : "/home/plex/attractfolder/emulators/"
}
)
